apptanksas/horus-sync-php

.github/workflows/pull_requests.yml
.github/workflows/tag_releases.yml
changelog.md
readme.md
src/Illuminate/Console/CreateEntitySynchronizableCommand.php

* update workflow tag_releases to create release in github
* update pull request rules

Release 0.1.5

---

changelog.md
readme.md
src/Application/Sync/SyncQueueActions.php
src/Core/Config/Config.php
src/Core/Config/Restriction/EntityRestriction.php
src/Core/Config/Restriction/MaxCountEntityRestriction.php
src/Core/Exception/RestrictionException.php
src/Core/Repository/EntityRepository.php
src/Horus.php
src/Illuminate/Console/PruneFilesUploadedCommand.php
src/Illuminate/Http/Controller.php
src/Illuminate/Http/Controller/Data/PostSyncQueueActionsController.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Application/Sync/SyncQueueActionsTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Added feature to add entity restrictions where it can define a max count of entities.
- Fixed parse expiration days param in prune upload files command.

🚀 Release: 0.3.0

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/GetMigrationSchemaApiTest.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Feature/Api/ValidateEntitiesDataApiTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php
tests/_Stubs/ParentFakeEntityFactory.php
tests/_Stubs/ParentFakeWritableEntity.php

- Fix insert parameter type as timestamp.

🚀 Release: 0.3.3

---

changelog.md
src/Illuminate/Database/WritableEntitySynchronizable.php

Data type fixed in entity definition

🚀 Release: 0.3.4

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php

order fixed when dropping entity tables

🚀 Release/ 0.3.5

---

changelog.md
composer.json
composer.lock
readme.md
src/Application/Sync/SyncQueueActions.php

🚀 Release: 0.3.6

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Fixed update entity when it has its receives a timestamp.

🚀 Release: 0.3.7

---

changelog.md
src/Illuminate/Database/WritableEntitySynchronizable.php
src/Repository/EloquentEntityRepository.php

- Fixed entity parsing when executing a delete operation.

🚀Release: 0.3.8

---

changelog.md
src/Repository/EloquentEntityRepository.php

- Fixed when its updating entity without changes.

🚀 Release: 0.3.9

---

changelog.md
src/Core/Entity/SyncParameter.php
src/Illuminate/Database/EntitySynchronizable.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/GetMigrationSchemaApiTest.php

- Added support to setup if a foreing entity is delete on cascade.

🚀Release: 0.4.0

---

changelog.md
readme.md
src/Core/Config/Restriction/FilterEntityRestriction.php
src/Core/Config/Restriction/MaxCountEntityRestriction.php
src/Core/Config/Restriction/valueObject/ParameterFilter.php
src/Illuminate/Database/ReadableEntitySynchronizable.php
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/GetDataEntitiesApiTest.php
tests/Feature/Api/GetDataEntityApiTest.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Core/File/FilePathGeneratorTest.php
tests/Unit/Repository/EloquentEntityAccessValidatorRepositoryTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php
tests/_Stubs/ReadableFakeEntity.php
tests/_Stubs/ReadableFakeEntityFactory.php

This pull request introduces a new `FilterEntityRestriction` feature to filter entity data based on specific criteria, along with updates to tests and refactoring for improved maintainability. The most significant changes include the implementation of the `FilterEntityRestriction` class, integration into the repository logic, and updates to tests to reflect the new functionality.
* Added `FilterEntityRestriction` class to enable filtering of entities based on parameters. This class includes properties for the entity name and filtering criteria (`src/Core/Config/Restriction/FilterEntityRestriction.php`, `[src/Core/Config/Restriction/valueObject/ParameterFilter.phpR1-R14](diffhunk://#diff-f4e96687b4fab2d78cb731126ee99811a2025e816f5aaf13652f5359b7e3694cR1-R14)`).
* Introduced …

New Entity Restriction [FilterEntityRestriction]

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php
readme.md
src/Core/Config/Restriction/FilterEntityRestriction.php
src/Core/Config/Restriction/MaxCountEntityRestriction.php
src/Core/Config/Restriction/valueObject/ParameterFilter.php
src/Core/Entity/SyncParameter.php
src/Core/Entity/SyncParameterType.php
src/Illuminate/Database/EntitySynchronizable.php
src/Illuminate/Database/ReadableEntitySynchronizable.php
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/GetDataEntitiesApiTest.php
tests/Feature/Api/GetDataEntityApiTest.php
tests/Feature/Api/GetMigrationSchemaApiTest.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Core/File/FilePathGeneratorTest.php
tests/Unit/Repository/EloquentEntityAccessValidatorRepositoryTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php
tests/_Stubs/ParentFakeWritableEntity.php
tests/_Stubs/ReadableFakeEntity.php
tests/_Stubs/ReadableFakeEntityFactory.php

- A new entity restriction is available [FilterEntityRestriction] to filter the data that can be downloaded to client based on certain criteria.
- Added new parameter type to defines a custom type with own regex.

🚀Release: 0.5.0

---

changelog.md
src/Illuminate/Console/CreateEntitySynchronizableCommand.php

- Fixed option in create entity synchronizable using artisan command.

🚀Release: 0.5.1

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php

- Fixed applying constraint in parameter custom.

🚀 Release: 0.5.2

---

changelog.md
src/Illuminate/Database/ReadableEntitySynchronizable.php
src/Repository/EloquentEntityRepository.php

- Added support to use UUID in readable entity.

🚀 Release: 0.5.3

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php

- Fixed applying constraint in parameter custom.

🚀 Release: 0.5.4

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php
src/Core/Entity/SyncParameter.php
tests/_Stubs/AdjacentFakeWritableEntity.php
tests/_Stubs/ChildFakeWritableEntity.php

- Turn off by default delete on cascade in parameter types.

🚀 Release: 0.5.5

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php
src/Core/Hasher.php
tests/_Stubs/Core/HasherTest.php

- Fixed migration when an parameter is nullable with entity linked.
- Fixed hashing data with null and boolean values.

🚀Release: 0.5.6

---

changelog.md
database/migrations/2024_06_05_00001_create_table_sync_queue_actions.php
src/Client/HorusQueueActionClient.php
src/Core/Mapper/QueueActionMapper.php
src/Core/Model/QueueAction.php
src/Illuminate/Database/SyncQueueActionModel.php
src/Illuminate/Http/Controller/Data/PostSyncQueueActionsController.php
src/Repository/EloquentQueueActionRepository.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Repository/EloquentQueueActionRepositoryTest.php
tests/_Stubs/Client/HorusQueueActionClientTest.php
tests/_Stubs/QueueActionFactory.php
tests/_Stubs/SyncQueueActionModelFactory.php

- Added new column in queue action to store the entity id.
- Added HorusQueueAction to query the queue action.

🚀Release: 0.6.0

---

changelog.md
database/migrations/2024_06_05_00001_create_table_sync_queue_actions.php
src/Application/Sync/SyncQueueActions.php
src/Client/HorusQueueActionClient.php
src/Client/IHorusQueueActionClient.php
src/Core/Model/QueueAction.php
src/Core/Validator/EntityRestrictionValidator.php
src/Illuminate/Database/SyncQueueActionModel.php
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/EloquentQueueActionRepository.php
tests/Feature/Client/PushActionClientTest.php
tests/Unit/Repository/EloquentQueueActionRepositoryTest.php
tests/_Stubs/Client/HorusQueueActionClientTest.php
tests/_Stubs/QueueActionFactory.php

- Added method to push actions in horus queue action client.

🚀Release: 0.8.0

---

changelog.md
composer.json
composer.lock
readme.md
routes/api_v1.php
src/Application/Get/GetDataSharedEntities.php
src/Core/Config/Config.php
src/Core/Repository/CacheRepository.php
src/Core/Repository/EntityRepository.php
src/Horus.php
src/Illuminate/Http/Controller/Data/GetSharedEntitiesController.php
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/DefaultCacheRepository.php
src/Repository/EloquentEntityRepository.php
src/RouteName.php
tests/Feature/Api/GetDataSharedEntitiesApiTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Added support to  shared entities. 
- update prefix api routes to horus/v1.

🚀 Release: 0.9.0

---

changelog.md
readme.md
src/Core/Config/Config.php
src/Horus.php
tests/Feature/Api/GetDataSharedEntitiesApiTest.php

- Added method setupOnSharedEntities to setup the shared entities when Horus needs it.

🚀 Release: 0.9.1

---

changelog.md
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/EloquentEntityRepository.php

- Added validation entities mapper in eloquent entity repository.

🚀 Release: 0.9.2

---

changelog.md
src/Illuminate/Provider/HorusServiceProvider.php

- Change bind entity repository dependency.

🚀 Release: 0.9.3

---

changelog.md
src/Core/Hasher.php
tests/_Stubs/Core/HasherTest.php

- Fixed issue hashing with float values.

🚀Release: 0.9.2

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Fixed sorting insert operation in entity repository.

🚀Release: 0.9.5

---

changelog.md
src/Illuminate/Provider/HorusServiceProvider.php
src/Repository/EloquentEntityRepository.php
tests/Unit/Core/File/FilePathGeneratorTest.php
tests/Unit/Repository/EloquentEntityAccessValidatorRepositoryTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Added cache to get readable entities.

🚀 Release: 0.10.0

---

changelog.md
src/Application/Sync/SyncQueueActions.php
src/Core/Mapper/EntityMapper.php
src/Core/Model/EntityDelete.php
src/Core/Model/EntityInsert.php
src/Core/Model/EntityOperation.php
src/Core/Model/EntityUpdate.php
src/Core/Model/QueueAction.php
src/Core/Repository/EntityRepository.php
src/Repository/DefaultCacheRepository.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Application/Sync/SyncQueueActionsTest.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Fixed issue a user wanted to make operations with a primary entity that is not shared.

🚀 Release: 0.10.2

---

changelog.md
src/Application/Sync/StartGenerateSyncDataJob.php
src/Illuminate/Http/Controller/Data/PostStartSyncDataJobController.php
tests/Feature/Api/PostStartSyncDataJobApiTest.php
tests/Unit/Application/Sync/StartGenerateSyncDataJobTest.php

- Fix endpoint start sync to receive the after parameter to filter the entities that are going to be updated.

🚀 Release: 0.11.1

---

changelog.md
src/Core/Model/EntityData.php
src/Repository/EloquentEntityRepository.php

- Fix entity data with attributes relations.

🚀 Release: 0.11.4

---

changelog.md
src/Illuminate/Job/GenerateDataSyncJob.php
tests/Unit/Illuminate/Job/GenerateDataSyncJobTest.php

- The file generated in the synchronization data is no longer of type application/json, but is now of type application/nd-json so that it can be processed line by line.

🚀 Release: 0.11.5

---

changelog.md
src/Application/Get/BaseGetEntities.php
src/Illuminate/Job/GenerateDataSyncJob.php
src/Illuminate/Util/EntitiesDataParser.php
tests/Unit/Illuminate/Job/GenerateDataSyncJobTest.php

- Flattened the entities data in the synchronization data to make it easier to process.

🚀 Release: 0.11.6

---

changelog.md
src/Illuminate/Job/GenerateDataSyncJob.php
tests/Unit/Illuminate/Job/GenerateDataSyncJobTest.php
tests/Unit/sample_sync_data.json

🚀 Release: 0.11.7

---

changelog.md
src/Core/Exception/OperationNotPermittedException.php

- Fix message in operation not permitted exception.

🚀 Release: 0.11.9

---

changelog.md
src/Application/Sync/SyncQueueActions.php
src/Core/Entity/EntityDependsOn.php
src/Illuminate/Console/PruneFilesUploadedCommand.php
src/Repository/EloquentEntityAccessValidatorRepository.php
src/Repository/EloquentEntityRepository.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/_Stubs/AdjacentFakeWritableEntity.php
tests/_Stubs/ChildFakeWritableEntity.php

- Fix prune files with query params url.
- Fix issue when get entity parent owner in sync actions with inserts.

🚀 Release: 0.11.12

---

changelog.md
src/Application/Get/GetQueueActions.php
tests/Feature/Api/GetSyncQueueActionsApiTest.php

- Fix issue in response format in get actions endpoint.

🚀 Release: 0.11.14

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Implemented upset in eloquent entity repository to update or insert entities.

🚀Release: 0.11.15

---

changelog.md
src/Application/Get/GetEntityHashes.php
src/Application/Validate/ValidateEntitiesData.php
src/Illuminate/Http/Controller/Data/ValidateEntitiesDataController.php
src/Illuminate/Http/Controller/Hashing/GetEntityHashesController.php
tests/Feature/Api/GetEntityHashesApiTest.php
tests/Feature/Api/ValidateEntitiesDataApiTest.php

- Added user id parameter in get entities hashes endpoint.
- Added user id parameter in validate entities data endpoint.

🚀 Release: 0.11.17

---

changelog.md
src/Application/Get/GetDataEntities.php
src/Application/Sync/SyncQueueActions.php
src/Core/Auth/UserAuth.php
src/Core/File/FilePathGenerator.php
src/Core/Validator/EntityRestrictionValidator.php
src/Illuminate/Http/Controller/Data/GetDataEntitiesController.php
src/Repository/EloquentEntityRepository.php

- Fixed cache search entities.
- Added group entities by owner and sync queue actions.

🚀Release: 0.11.20

---

changelog.md
src/Illuminate/Job/GenerateDataSyncJob.php
tests/Unit/Illuminate/Job/GenerateDataSyncJobTest.php

- Fix sort entities generate data sync job.

🚀Release: 0.11.21

---

changelog.md
tests/Feature/Api/PostStartSyncDataJobApiTest.php

- Fix generate data sync job dependency with entity mapper.

🚀Release: 0.11.22

---

changelog.md
src/Application/Validate/ValidateEntitiesData.php
src/Core/Config/Config.php
src/Core/Config/FeatureName.php
src/Illuminate/Http/Controller/Data/ValidateEntitiesDataController.php
src/Illuminate/Provider/HorusServiceProvider.php
tests/Feature/Api/ValidateEntitiesDataApiTest.php

- Added configuration to disabled features.

🚀 Release: 0.12.0

---

changelog.md
readme.md
src/Core/Config/Restriction/MaxCountEntityRestriction.php
src/Core/Validator/EntityRestrictionValidator.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Application/Sync/SyncQueueActionsTest.php
tests/_Stubs/Client/HorusQueueActionClientTest.php

- Refactor setup Max entity count restriction.

🚀 Release: 0.12.4

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Fixed issue in insert entities with optional parameters.

🚀Release: 0.12.5

---

changelog.md
src/Repository/EloquentEntityRepository.php
tests/Unit/Repository/EloquentEntityRepositoryTest.php

- Fixed filter duplicate entities in insert operations.

🚀Release: 0.12.7

---

changelog.md
src/Application/Sync/SyncQueueActions.php
src/Core/Config/Config.php
src/Core/File/FileReferenceValidator.php
src/Core/File/IFileReferenceValidator.php
src/Illuminate/Console/PruneFilesUploadedCommand.php
src/Illuminate/Database/EntitySynchronizable.php
src/Illuminate/Provider/HorusServiceProvider.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Illuminate/Console/PruneFilesUploadedCommandTest.php
tests/_Stubs/ParentFakeEntityFactory.php

- Improved prune upload files command to delete files, validating linking entities.

🚀 Release: 0.13.0

---

changelog.md
src/Illuminate/Console/PruneFilesUploadedCommand.php

- Fixed prune file command using pgsql database validating uuid columns.

🚀Release: 0.13.2

---

changelog.md
src/Core/File/FileReferenceValidator.php
tests/Unit/Application/Sync/SyncQueueActionsTest.php

- Fixed delete file pending in file reference validator.

🚀Release: 0.13.3

---

changelog.md
database/migrations/2025_10_04_00001_update_column_action_in_sync_queue_actions.php
src/Core/Factory/EntityOperationFactory.php
src/Core/Mapper/QueueActionMapper.php
src/Core/SyncAction.php
src/Illuminate/Http/Controller/Data/PostSyncQueueActionsController.php
tests/Feature/Api/PostSyncQueueActionsApiTest.php
tests/Unit/Repository/EloquentQueueActionRepositoryTest.php
tests/_Stubs/QueueActionFactory.php
tests/_Stubs/SyncQueueActionModelFactory.php

- Added new sync action "UPDELETE" to update or delete an entity from client side.

🚀Release: 0.14.0

---

changelog.md
database/migrations/2024_06_05_00002_create_sync_entities.php
src/Illuminate/Migration/EntityMigrator.php

- Added Entity Migrator to migrate entities data through the time.

🚀 Release: 0.14.1

---

changelog.md
database/migrations/2025_10_04_00001_update_column_action_in_sync_queue_actions.php
src/Core/Factory/EntityOperationFactory.php
tests/Unit/Core/EntityMapTest.php
tests/Unit/Core/Factory/EntityOperationFactoryTest.php
tests/Unit/Core/HasherTest.php

- Fixed migration to update column action in horus_queue_actions table.
- Added filter attributes reserved in entity operation definition.

🚀 Release: 0.14.2
